

version: '3.1'

services:

    cloud_db:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
        environment:
            - "cluster.name=db-cluster"
            - "node.name=cloud_db"
            - "node.master=true"
            - "node.data=true"
            - 'ES_JAVA_OPTS=-Xms4096m -Xmx4096m'
            - 'NO_PROXY=*'
            - 'no_proxy=*'
        networks:
            - db_net
        deploy:
            placement:
                constraints: [node.role==manager]

    cloud_web:
        image: smtc_web_cloud:latest
        ports:
            - "443:8080"
        environment:
            DBHOST: 'http://cloud_db:9200'
            NO_PROXY: '*'
            no_proxy: '*'
        volumes:
            - /etc/localtime:/etc/localtime:ro
        secrets:
            - source: self_crt
              target: self.crt
              uid: ${USER_ID}
              gid: ${GROUP_ID}
              mode: 0444
            - source: self_key
              target: self.key
              uid: ${USER_ID}
              gid: ${GROUP_ID}
              mode: 0440
            - source: dhparam_pem
              target: dhparam.pem
              uid: ${USER_ID}
              gid: ${GROUP_ID}
              mode: 0444
        networks:
            - cloud_net
            - db_net
            - office1_net
            - office2_net
            - office3_net
        deploy:
            placement:
                constraints: [node.role==manager]


    office1_db:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
        environment:
            - cluster.name=db-cluster'
            - 'node.name=office1_db'
            - 'node.master=true'
            - 'node.data=true'
            - 'discovery.zen.minimum_master_nodes=1'
            - 'discovery.zen.ping.unicast.hosts=cloud_db'
            - 'ES_JAVA_OPTS=-Xms4096m -Xmx4096m'
            - 'NO_PROXY=*'
            - 'no_proxy=*'
        networks:
            - db_net
        deploy:
            placement:
                constraints: [node.labels.office1_zone==yes]
'
    office1_web:
        image: smtc_web_local:latest
        environment:
            DBHOST: 'http://office1_db:9200'
            OFFICE: '45.539664,-122.937729'
            NO_PROXY: '*'
            no_proxy: '*'
        volumes:
            - ${STORAGE_VOLUME}:/mnt/storage:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - db_net
            - office1_net
        deploy:
            placement:
                constraints: [node.labels.office1_zone==yes]

    office1_cleanup:
        image: smtc_storage_cleanup:latest
        volumes:
            - ${STORAGE_VOLUME}:/mnt/storage:rw
        environment:
            INDEXES: 'recordings,analytics'
            RETENTION_TIME: '14400'
            SERVICE_INTERVAL: '14400'
            OFFICE: '45.539664,-122.937729'
            DBHOST: 'http://office1_db:9200'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office1_net
        deploy:
            placement:
                constraints: [node.labels.office1_zone==yes]

    office1_camera_discovery:
        image: smtc_onvif_discovery:latest
        environment:
            IP_SCAN_RANGE: '192.168.1.0/24'
            PORT_SCAN_RANGE: '0-65535'
            OFFICE: '45.539664,-122.937729'
            DISTANCE: 10
            ANGLEOFFSET: 15
            DBHOST: 'http://office1_db:9200'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office1_net
        deploy:
            placement:
                constraints: [node.labels.office1_zone==yes]

    office1_health_check:
        image: smtc_trigger_health
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            SERVICE_INTERVAL: '300'
            OFFICE: '45.539664,-122.937729'
            DBHOST: 'http://office1_db:9200'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office1_net
        deploy:
            placement:
                constraints: [node.labels.office1_zone==yes]

    office1_where_indexing:
        image: smtc_where_indexing
        environment:
            INDEXES: 'recordings,analytics'
            OFFICE: '45.539664,-122.937729'
            DBHOST: 'http://office1_db:9200'
            SERVICE_INTERVAL: '30'
            UPDATE_INTERVAL: '5'
            SEARCH_BATCH: '3000'
            UPDATE_BATCH: '500'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office1_net
        deploy:
            placement:
                constraints: [node.labels.office1_zone==yes]

    office1_analytics:
        image: smtc_analytics_object_detection:latest
        environment:
            OFFICE: '45.539664,-122.937729'
            DBHOST: 'http://office1_db:9200'
            MQTTHOST: 'office1_mqtt'
            EVERY_NTH_FRAME: 6
            NO_PROXY: '*'
            no_proxy: '*'
        volumes:
            - ${STORAGE_VOLUME}:/home/video-analytics/app/server/recordings:rw
            - /etc/localtime:/etc/localtime:ro
        networks:
            - db_net
            - office1_net
        deploy:
            replicas: 3
            placement:
                constraints: [node.labels.office1_zone==yes]

    office1_mqtt:
        image: eclipse-mosquitto:1.5.8
        environment:
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - office1_net
        deploy:
            placement:
                constraints: [node.labels.office1_zone==yes]

    office1_simulated_cameras:
        image: smtc_sensor_simulation:latest
        environment:
            OFFICE: '45.539664,-122.937729'
            DISTANCE: '20'
            SENSORS: '3'
            SENSOR_ID: '{{.Task.Slot}}'
            DBHOST: 'http://office1_db:9200'
            FILES: '.mp4$$'
            THETA: 105
            MNTH: 15.0
            ALPHA: 45
            FOVH: 90
            FOVV: 68
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office1_net
            - office1_camera_net
        deploy:
            replicas: 3
            placement:
                constraints: [node.labels.office1_zone==yes]


    office2_db:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
        environment:
            - cluster.name=db-cluster'
            - 'node.name=office2_db'
            - 'node.master=true'
            - 'node.data=true'
            - 'discovery.zen.minimum_master_nodes=1'
            - 'discovery.zen.ping.unicast.hosts=cloud_db'
            - 'ES_JAVA_OPTS=-Xms4096m -Xmx4096m'
            - 'NO_PROXY=*'
            - 'no_proxy=*'
        networks:
            - db_net
        deploy:
            placement:
                constraints: [node.labels.office2_zone==yes]
'
    office2_web:
        image: smtc_web_local:latest
        environment:
            DBHOST: 'http://office2_db:9200'
            OFFICE: '45.548651,-122.965623'
            NO_PROXY: '*'
            no_proxy: '*'
        volumes:
            - ${STORAGE_VOLUME}:/mnt/storage:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - db_net
            - office2_net
        deploy:
            placement:
                constraints: [node.labels.office2_zone==yes]

    office2_cleanup:
        image: smtc_storage_cleanup:latest
        volumes:
            - ${STORAGE_VOLUME}:/mnt/storage:rw
        environment:
            INDEXES: 'recordings,analytics'
            RETENTION_TIME: '14400'
            SERVICE_INTERVAL: '14400'
            OFFICE: '45.548651,-122.965623'
            DBHOST: 'http://office2_db:9200'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office2_net
        deploy:
            placement:
                constraints: [node.labels.office2_zone==yes]

    office2_camera_discovery:
        image: smtc_onvif_discovery:latest
        environment:
            IP_SCAN_RANGE: '192.168.2.0/24'
            PORT_SCAN_RANGE: '0-65535'
            OFFICE: '45.548651,-122.965623'
            DISTANCE: 10
            ANGLEOFFSET: 15
            DBHOST: 'http://office2_db:9200'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office2_net
        deploy:
            placement:
                constraints: [node.labels.office2_zone==yes]

    office2_health_check:
        image: smtc_trigger_health
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            SERVICE_INTERVAL: '300'
            OFFICE: '45.548651,-122.965623'
            DBHOST: 'http://office2_db:9200'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office2_net
        deploy:
            placement:
                constraints: [node.labels.office2_zone==yes]

    office2_where_indexing:
        image: smtc_where_indexing
        environment:
            INDEXES: 'recordings,analytics'
            OFFICE: '45.548651,-122.965623'
            DBHOST: 'http://office2_db:9200'
            SERVICE_INTERVAL: '30'
            UPDATE_INTERVAL: '5'
            SEARCH_BATCH: '3000'
            UPDATE_BATCH: '500'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office2_net
        deploy:
            placement:
                constraints: [node.labels.office2_zone==yes]

    office2_analytics:
        image: smtc_analytics_object_detection:latest
        environment:
            OFFICE: '45.548651,-122.965623'
            DBHOST: 'http://office2_db:9200'
            MQTTHOST: 'office2_mqtt'
            EVERY_NTH_FRAME: 6
            NO_PROXY: '*'
            no_proxy: '*'
        volumes:
            - ${STORAGE_VOLUME}:/home/video-analytics/app/server/recordings:rw
            - /etc/localtime:/etc/localtime:ro
        networks:
            - db_net
            - office2_net
        deploy:
            replicas: 3
            placement:
                constraints: [node.labels.office2_zone==yes]

    office2_mqtt:
        image: eclipse-mosquitto:1.5.8
        environment:
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - office2_net
        deploy:
            placement:
                constraints: [node.labels.office2_zone==yes]

    office2_simulated_cameras:
        image: smtc_sensor_simulation:latest
        environment:
            OFFICE: '45.548651,-122.965623'
            DISTANCE: '20'
            SENSORS: '3'
            SENSOR_ID: '{{.Task.Slot}}'
            DBHOST: 'http://office2_db:9200'
            FILES: '.mp4$$'
            THETA: 105
            MNTH: 15.0
            ALPHA: 45
            FOVH: 90
            FOVV: 68
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office2_net
            - office2_camera_net
        deploy:
            replicas: 3
            placement:
                constraints: [node.labels.office2_zone==yes]


    office3_db:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
        environment:
            - cluster.name=db-cluster'
            - 'node.name=office3_db'
            - 'node.master=true'
            - 'node.data=true'
            - 'discovery.zen.minimum_master_nodes=1'
            - 'discovery.zen.ping.unicast.hosts=cloud_db'
            - 'ES_JAVA_OPTS=-Xms4096m -Xmx4096m'
            - 'NO_PROXY=*'
            - 'no_proxy=*'
        networks:
            - db_net
        deploy:
            placement:
                constraints: [node.labels.office3_zone==yes]
'
    office3_web:
        image: smtc_web_local:latest
        environment:
            DBHOST: 'http://office3_db:9200'
            OFFICE: '45.540001,-122.993239'
            NO_PROXY: '*'
            no_proxy: '*'
        volumes:
            - ${STORAGE_VOLUME}:/mnt/storage:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - db_net
            - office3_net
        deploy:
            placement:
                constraints: [node.labels.office3_zone==yes]

    office3_cleanup:
        image: smtc_storage_cleanup:latest
        volumes:
            - ${STORAGE_VOLUME}:/mnt/storage:rw
        environment:
            INDEXES: 'recordings,analytics'
            RETENTION_TIME: '14400'
            SERVICE_INTERVAL: '14400'
            OFFICE: '45.540001,-122.993239'
            DBHOST: 'http://office3_db:9200'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office3_net
        deploy:
            placement:
                constraints: [node.labels.office3_zone==yes]

    office3_camera_discovery:
        image: smtc_onvif_discovery:latest
        environment:
            IP_SCAN_RANGE: '192.168.3.0/24'
            PORT_SCAN_RANGE: '0-65535'
            OFFICE: '45.540001,-122.993239'
            DISTANCE: 10
            ANGLEOFFSET: 15
            DBHOST: 'http://office3_db:9200'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office3_net
        deploy:
            placement:
                constraints: [node.labels.office3_zone==yes]

    office3_health_check:
        image: smtc_trigger_health
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            SERVICE_INTERVAL: '300'
            OFFICE: '45.540001,-122.993239'
            DBHOST: 'http://office3_db:9200'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office3_net
        deploy:
            placement:
                constraints: [node.labels.office3_zone==yes]

    office3_where_indexing:
        image: smtc_where_indexing
        environment:
            INDEXES: 'recordings,analytics'
            OFFICE: '45.540001,-122.993239'
            DBHOST: 'http://office3_db:9200'
            SERVICE_INTERVAL: '30'
            UPDATE_INTERVAL: '5'
            SEARCH_BATCH: '3000'
            UPDATE_BATCH: '500'
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office3_net
        deploy:
            placement:
                constraints: [node.labels.office3_zone==yes]

    office3_analytics:
        image: smtc_analytics_object_detection:latest
        environment:
            OFFICE: '45.540001,-122.993239'
            DBHOST: 'http://office3_db:9200'
            MQTTHOST: 'office3_mqtt'
            EVERY_NTH_FRAME: 6
            NO_PROXY: '*'
            no_proxy: '*'
        volumes:
            - ${STORAGE_VOLUME}:/home/video-analytics/app/server/recordings:rw
            - /etc/localtime:/etc/localtime:ro
        networks:
            - db_net
            - office3_net
        deploy:
            replicas: 3
            placement:
                constraints: [node.labels.office3_zone==yes]

    office3_mqtt:
        image: eclipse-mosquitto:1.5.8
        environment:
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - office3_net
        deploy:
            placement:
                constraints: [node.labels.office3_zone==yes]

    office3_simulated_cameras:
        image: smtc_sensor_simulation:latest
        environment:
            OFFICE: '45.540001,-122.993239'
            DISTANCE: '20'
            SENSORS: '3'
            SENSOR_ID: '{{.Task.Slot}}'
            DBHOST: 'http://office3_db:9200'
            FILES: '.mp4$$'
            THETA: 105
            MNTH: 15.0
            ALPHA: 45
            FOVH: 90
            FOVV: 68
            NO_PROXY: '*'
            no_proxy: '*'
        networks:
            - db_net
            - office3_net
            - office3_camera_net
        deploy:
            replicas: 3
            placement:
                constraints: [node.labels.office3_zone==yes]



networks:
    db_net:
    cloud_net:
    office1_net:
    office1_camera_net:
    office2_net:
    office2_camera_net:
    office3_net:
    office3_camera_net:


secrets:
    self_key:
        file: ../certificate/self.key
    self_crt:
        file: ../certificate/self.crt
    dhparam_pem:
        file: ../certificate/dhparam.pem

