
version: '3.1'

services:

    database:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
        environment:
            - 'discovery.type=single-node'
            - 'ES_JAVA_OPTS=-Xms4096m -Xmx4096m'
            - 'NO_PROXY=*'
            - 'no_proxy=*'

    web_cloud:
        image: smtc_web_cloud:latest
        ports:
            - "443:8080"
        environment:
            DBHOST: 'http://database:9200'
            NO_PROXY: '*'
            no_proxy: '*'
        secrets:
            - source: self_crt
              target: self.crt
              uid: ${USER_ID}
              gid: ${GROUP_ID}
              mode: 0444
            - source: self_key
              target: self.key
              uid: ${USER_ID}
              gid: ${GROUP_ID}
              mode: 0440
            - source: dhparam_pem
              target: dhparam.pem
              uid: ${USER_ID}
              gid: ${GROUP_ID}
              mode: 0444
        
    web_street:
        image: smtc_web_local:latest
        environment:
            DBHOST: 'http://database:9200'
            OFFICE: '45.543797,-122.962038'
            NO_PROXY: '*'
            no_proxy: '*'
        volumes:
            - ${STORAGE_VOLUME}:/mnt/storage:ro
            - /etc/localtime:/etc/localtime:ro

    simulated_camera_street_sensor1:
        image: smtc_sensor_simulation:latest
        environment:
            OFFICE: '45.543797,-122.962038'
            LOCATION: '45.550043,-122.973526'
            DBHOST: 'http://database:9200'
            FILES: '.mp4$$'
            SENSOR_ID: 0
            THETA: 105
            MNTH: 15.0
            ALPHA: 45
            FOVH: 90
            FOVV: 68
            NO_PROXY: '*'
            no_proxy: '*'
         
    simulated_camera_street_sensor2:
        image: smtc_sensor_simulation:latest
        environment:
            OFFICE: '45.543797,-122.962038'
            LOCATION: '45.538905,-122.972792'
            DBHOST: 'http://database:9200'
            FILES: '.mp4$$'
            SENSOR_ID: 1
            THETA: 105
            MNTH: 15.0
            ALPHA: 45
            FOVH: 90
            FOVV: 68
            NO_PROXY: '*'
            no_proxy: '*'
         
    simulated_camera_street_sensor3:
        image: smtc_sensor_simulation:latest
        environment:
            OFFICE: '45.543797,-122.962038'
            LOCATION: '45.536643,-122.957053'
            DBHOST: 'http://database:9200'
            FILES: '.mp4$$'
            SENSOR_ID: 2
            THETA: 105
            MNTH: 15.0
            ALPHA: 45
            FOVH: 90
            FOVV: 68
            NO_PROXY: '*'
            no_proxy: '*'
         
    storage_cleanup_street:
        image: smtc_storage_cleanup:latest
        volumes:
            - ${STORAGE_VOLUME}:/mnt/storage:rw
        environment:
            INDEXES: 'recordings,analytics'
            RETENTION_TIME: '14400'
            SERVICE_INTERVAL: '14400'
            OFFICE: '45.543797,-122.962038'
            DBHOST: 'http://database:9200'
            NO_PROXY: '*'
            no_proxy: '*'

    onvif-discovery_street:
        image: smtc_onvif_discovery:latest
        environment:
            IP_SCAN_RANGE: '192.168.1.0/24'
            PORT_SCAN_RANGE: '0-65535'
            OFFICE: '45.543797,-122.962038'
            DISTANCE: 10
            ANGLEOFFSET: 15
            DBHOST: 'http://database:9200'
            NO_PROXY: '*'
            no_proxy: '*'

    health_check_street:
        image: smtc_trigger_health
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            SERVICE_INTERVAL: '300'
            OFFICE: '45.543797,-122.962038'
            DBHOST: 'http://database:9200'
            NO_PROXY: '*'
            no_proxy: '*'

    where_indexing_street:
        image: smtc_where_indexing
        environment:
            INDEXES: 'recordings,analytics'
            OFFICE: '45.543797,-122.962038'
            DBHOST: 'http://database:9200'
            SERVICE_INTERVAL: '30'
            UPDATE_INTERVAL: '5'
            SEARCH_BATCH: '3000'
            UPDATE_BATCH: '500'
            NO_PROXY: '*'
            no_proxy: '*'

    analytics_street:
        image: smtc_analytics_object_detection:latest
        environment:
            OFFICE: '45.543797,-122.962038'
            DBHOST: 'http://database:9200'
            MQTTHOST: 'mqtt'
            STORAGE_VOLUME: '/home/video-analytics/app/server/recordings'
            EVERY_NTH_FRAME: 6
            NO_PROXY: '*'
            no_proxy: '*'
        volumes:
            - ${STORAGE_VOLUME}:/home/video-analytics/app/server/recordings:rw
            - /etc/localtime:/etc/localtime:ro
        deploy:
            replicas: 3
    
    mqtt:
        image: eclipse-mosquitto:1.5.8
        environment:
            NO_PROXY: '*'
            no_proxy: '*'

secrets:
    self_key:
        file: ../certificate/self.key
    self_crt:
        file: ../certificate/self.crt
    dhparam_pem:
        file: ../certificate/dhparam.pem
